realsense_fov: 1.204277184 # radians
realsense_res_x: 1920 #pixel width of image frames
angle_error_adjustment: 0.0 #radians TUNING
marker_base_diameter_for_filtering: 0.5 #meters - actually 0.457 m TUNING
marker_radius_for_fitlering: 0.14 #meters - actually 0.127 m TUNING
max_lidar_range: 29 #meters - should be slightly less than real range, or accurate range 
min_lidar_range: 0.1 #meters - should be slight larger than real, or accurate range
prop_coord_range: 0.1 #meters, used to create a 'bubble' around identified prop so that it doesn't remap the same prop TUNING
coord_mapping_error_estimation: 2 #meters TUNING
degrees_lat_per_meter: 9.02455226019e-06
degrees_lon_per_meter: 1.01053264398e-05
